namespace SafeDiskCleaner.Core.Localization;

/// <summary>Polish strings.</summary>
internal static class Pl
{
    public static readonly IReadOnlyDictionary<string, string> Map = new Dictionary<string, string>
    {
        // Common
        ["Common.Cancel"] = "Anuluj",
        ["Common.Delete"] = "Usuń",
        ["Common.Restore"] = "Przywróć",
        ["Common.SelectAll"] = "Zaznacz wszystko",
        ["Common.Deselect"] = "Odznacz",
        ["Common.Clear"] = "Wyczyść",
        ["Common.Continue"] = "Kontynuuj",
        ["Common.Date"] = "Data",
        ["Common.Details"] = "Szczegóły",
        ["Common.Size"] = "Rozmiar",
        ["Common.Path"] = "Ścieżka",
        ["Common.Status"] = "Status",
        ["Common.Actions"] = "Akcje",
        ["Common.Action"] = "Akcja",
        ["Common.Browse"] = "Przeglądaj...",
        ["Common.OriginalPath"] = "Oryginalna ścieżka",
        ["Common.Original"] = "Oryginał",
        ["Common.LastAccess"] = "Ostatni dostęp",
        ["Common.ExportCsv"] = "Eksport CSV",
        ["Common.ExportCsvTooltip"] = "Zapisz raport kandydatów do pliku CSV",
        ["Common.ClearSelected"] = "Wyczyść zaznaczone",
        ["Common.CleanupResult"] = "Wynik czyszczenia",
        ["Common.NothingSelected"] = "Nic nie zaznaczono.",
        ["Common.ProcessedFreed"] = "Przetworzono {0}, zwolniono {1}.",
        ["Common.DryRunFreed"] = "Dry-run: zwolniłoby {0}.",
        ["Common.Error"] = "Błąd: {0}",
        ["C.DaysShort"] = "{0} dni",

        // Navigation / shell
        ["Nav.Dashboard"] = "Przegląd",
        ["Nav.Scan"] = "Skanowanie",
        ["Nav.Duplicates"] = "Duplikaty",
        ["Nav.Quarantine"] = "Kwarantanna",
        ["Nav.Settings"] = "Ustawienia",
        ["Nav.AuditLog"] = "Dziennik audytu",
        ["Nav.Apps"] = "Aplikacje",
        ["Apps.Title"] = "Aplikacje",
        ["Apps.Description"] = "Oficjalne deinstalatory programów zainstalowanych na tym komputerze. Najpierw próbowany jest tryb cichy, jeśli producent go przewidział.",
        ["Apps.NameCol"] = "Nazwa",
        ["Apps.VersionCol"] = "Wersja",
        ["Apps.PublisherCol"] = "Wydawca",
        ["Apps.SizeCol"] = "Rozmiar",
        ["Apps.UninstallBtn"] = "Odinstaluj",
        ["Apps.RefreshBtn"] = "Odśwież listę",
        ["Apps.Empty"] = "Nie znaleziono aplikacji z deinstalatorem.",
        ["Apps.ConfirmTitle"] = "Deinstalacja",
        ["Apps.ConfirmMsg"] = "Uruchomić oficjalny deinstalator „{0}”?",
        ["Apps.Launched"] = "Deinstalator „{0}” został uruchomiony.",
        ["Apps.Error"] = "Błąd deinstalacji: {0}",
        ["Apps.WindowsOnly"] = "Lista aplikacji jest dostępna tylko w systemie Windows.",
        ["Scan.TreemapToggle"] = "Mapa wyników",
        ["MainWindow.Subtitle"] = "Bezpieczna analiza i czyszczenie dysków Windows",
        ["MainWindow.SubtitleShort"] = "Bezpieczna analiza i czyszczenie dysków",

        // Dashboard
        ["Dash.Subtitle"] = "Stan dysków i statystyki czyszczenia",
        ["Dash.QuickActions"] = "Szybkie akcje",
        ["Dash.FreedHistory"] = "Zwolniono przez 14 dni",
        ["Dash.ScanNow"] = "Skanuj teraz",
        ["Dash.FreedTotal"] = "Zwolniono łącznie",
        ["Dash.InQuarantine"] = "Na kwarantannie",
        ["Dash.LastScan"] = "Ostatnie skanowanie",
        ["Dash.DrivesCount"] = "Dysków",
        ["Dash.UnderAnalysis"] = "analizowanych",
        ["Dash.Drives"] = "Dyski",

        // Audit
        ["Audit.Description"] = "Dziennik wszystkich operacji czyszczenia zapisywany w SQLite (EF Core).",
        ["Audit.ClearLog"] = "Wyczyść dziennik",
        ["Audit.EmptyTitle"] = "Dziennik jest pusty",
        ["Audit.EmptyText"] = "Tutaj pojawią się wszystkie wykonane operacje czyszczenia.",
        ["Audit.ConfirmClearMsg"] = "Wszystkie wpisy audytu zostaną usunięte. Kontynuować?",

        // Quarantine
        ["Quarantine.Description"] = "Pliki, które SafeDisk przeniósł przed usunięciem, aby można je było przywrócić. Tutaj możesz przywrócić je na miejsce lub usunąć bezpowrotnie. Okres przechowywania ustawiasz w „Ustawieniach”.",
        ["Quarantine.Clear"] = "Wyczyść kwarantannę",
        ["Quarantine.EmptyTitle"] = "Kwarantanna jest pusta",
        ["Quarantine.EmptyText"] = "Tutaj pojawią się pliki przeniesione przed trwałym usunięciem.",
        ["Quarantine.DeleteConfirmTitle"] = "Usuń z kwarantanny",
        ["Quarantine.DeleteConfirmMsg"] = "Plik zostanie usunięty bezpowrotnie:\n{0}",
        ["Quarantine.ClearConfirmMsg"] = "Wszystkie pliki na kwarantannie zostaną usunięte bezpowrotnie. Kontynuować?",
        ["Quarantine.Cleared"] = "Kwarantanna wyczyszczona ({0} wpisów).",
        ["Quarantine.RestoreFailed"] = "Nie udało się przywrócić: {0}",

        // Duplicates
        ["Dup.Title"] = "Wyszukiwanie duplikatów",
        ["Dup.Description"] = "Analizowane są pliki większe niż 4 KB według hasha BLAKE3. Zakres: ścieżki z karty „Skanowanie” lub wszystkie dyski, jeśli nie podano. Przy „Zaznacz wszystko” zawsze zachowywana jest jedna najnowsza kopia każdej grupy.",
        ["Dup.Find"] = "Znajdź duplikaty",
        ["Dup.Searching"] = "Wyszukiwanie...",
        ["Dup.ResultsTitle"] = "Duplikaty",
        ["Dup.NeedRoots"] = "Podaj ścieżki do analizy duplikatów.",
        ["Dup.NotFound"] = "Nie znaleziono duplikatów.",
        ["Dup.Found"] = "Znaleziono duplikatów: {0}.",
        ["Dup.Cancelled"] = "Wyszukiwanie duplikatów anulowano.",

        // Scan
        ["Scan.AreaTitle"] = "Zakres skanowania",
        ["Scan.CustomRootsHint"] = "Dodatkowe ścieżki do analizy (po przecinku)...",
        ["Scan.MediumCheckbox"] = "Medium (aktualizacje, pakiety)",
        ["Scan.ToRecycleBin"] = "Do kosza",
        ["Scan.ToRecycleBinTooltip"] = "Małe pliki są przenoszone do kosza Windows zamiast trwałego usunięcia. Duże pliki zawsze trafiają do kwarantanny SafeDisk.",
        ["Scan.NotUsedDays"] = "Niewykorzystane dni:",
        ["Scan.Analyze"] = "Analizuj",
        ["Scan.Scanning"] = "Skanowanie...",
        ["Scan.CleanRecycleBin"] = "Opróżnij kosz",
        ["Scan.CleanRecycleBinTooltip"] = "Trwale usuń wszystkie pliki z kosza Windows",
        ["Scan.Potential"] = "Potencjalnie do odzyskania",
        ["Scan.FilesScanned"] = "Przeskanowane pliki",
        ["Scan.CandidatesCount"] = "Kandydatów",
        ["Scan.ElapsedTime"] = "Czas analizy",
        ["Scan.Candidates"] = "Kandydaci",
        ["Scan.OnlySafe"] = "Tylko bezpieczne",
        ["Scan.OnlySafeTooltip"] = "Wybierz tylko kandydatów z poziomem ryzyka Safe",
        ["Scan.AutoClean"] = "Auto-czyszczenie",
        ["Scan.CleanSelected"] = "Wyczyść zaznaczone",
        ["Scan.Filters"] = "Filtry:",
        ["Scan.SearchHint"] = "Szukaj po ścieżce...",
        ["Scan.ResetFilters"] = "Resetuj filtry",
        ["Scan.PickFolders"] = "Wybierz foldery lub dyski do analizy",
        ["Scan.NoCandidates"] = "Nie znaleziono kandydatów do czyszczenia.",
        ["Scan.Completed"] = "Przeskanowano {0:N0} plików, znaleziono kandydatów: {1}.",
        ["Scan.Cancelled"] = "Skanowanie anulowano.",
        ["Scan.Error"] = "Błąd skanowania: {0}",
        ["Scan.DeleteWithoutBinTitle"] = "Usuwanie bez kosza",
        ["Scan.DeleteWithoutBinMsg"] = "Pliki nie będą przenoszone do kosza. Duże pliki trafią do kwarantanny SafeDisk. Kontynuować?",

        // Recycle bin
        ["RecycleBin.CleanConfirmTitle"] = "Opróżnianie kosza",
        ["RecycleBin.CleanConfirmMsg"] = "Spowoduje to trwałe usunięcie wszystkich plików z kosza. Kontynuować?",
        ["RecycleBin.Cleaned"] = "Kosz opróżniono.",
        ["RecycleBin.CleanFailed"] = "Nie udało się opróżnić kosza.",

        // Settings
        ["Settings.InterfaceCard"] = "Interfejs",
        ["Settings.Theme"] = "Motyw:",
        ["Settings.AccentColor"] = "Kolor akcentu:",
        ["Settings.Language"] = "Język:",
        ["Settings.CleaningCard"] = "Czyszczenie",
        ["Settings.RetentionDays"] = "Przechowywanie kwarantanny (dni):",
        ["Settings.AutoThreshold"] = "Próg pewności auto (%):",
        ["Settings.ProgramCard"] = "Program",
        ["Settings.Version"] = "Wersja:",
        ["Settings.DataDir"] = "Katalog danych:",
        ["Settings.CheckUpdates"] = "Sprawdź aktualizacje",
        ["Settings.ExclusionsCard"] = "Wyjątki",
        ["Settings.ScheduleCard"] = "Harmonogram czyszczenia",
        ["Settings.ScheduleEnable"] = "Uruchamiaj czyszczenie wg harmonogramu",
        ["Settings.ScheduleDaily"] = "Codziennie",
        ["Settings.ScheduleWeekly"] = "Co tydzień",
        ["Settings.ScheduleTimeLabel"] = "Godzina (HH:mm):",
        ["Settings.ScheduleApplied"] = "Harmonogram aktywowany.",
        ["Settings.ScheduleRemoved"] = "Harmonogram usunięto.",
        ["Settings.ScheduleUnsupported"] = "Planowanie nie jest obsługiwane w tym systemie.",
        ["Settings.ScheduleMissingCli"] = "Nie znaleziono SafeDiskCleaner.Cli obok aplikacji.",
        ["Settings.ScheduleError"] = "Błąd harmonogramu: {0}",
        ["Settings.ExclusionsHint"] = "Jeden na linię: ścieżka lub wzorzec z * i ?. Te ścieżki nigdy nie są skanowane.",
        ["Settings.UpdateAvailable"] = "Dostępna wersja {0}",
        ["Settings.UpToDate"] = "Zainstalowana najnowsza wersja ({0})",

        // Update flow
        ["Update.Checking"] = "Ładowanie...",
        ["Update.Installing"] = "Instalowanie...",
        ["Update.AvailablePrefix"] = "Dostępna wersja ",
        ["Update.Install"] = "Aktualizuj",

        // Filters / export / cleanup
        ["Filter.AllCategories"] = "Wszystkie kategorie",
        ["Filter.AllRisks"] = "Wszystkie ryzyka",
        ["Export.SaveReport"] = "Zapisz raport kandydatów",
        ["Export.Saved"] = "Raport zapisano: {0}",
        ["Export.Error"] = "Błąd eksportu: {0}",
        ["Cleanup.Error"] = "Błąd czyszczenia: {0}",

        // Grid columns
        ["Col.Category"] = "Kategoria",
        ["Col.Risk"] = "Ryzyko",
        ["Col.Recommendation"] = "Rekomendacja",

        // Inline fragments between bound runs
        ["Frag.FreeInline"] = " · wolne ",
        ["Frag.Selected"] = " zaznaczono · ",
        ["Frag.Of"] = " z ",
        ["Frag.Files"] = " plików · ",
        ["Frag.Candidates"] = " kandydatów",
        ["Frag.TotalPrefix"] = "· Łącznie ",
        ["Frag.Operations"] = " operacji",
        ["Frag.FilesWord"] = " plików",
        ["Frag.CandidatesWord"] = " kandydatów",
        ["Dash.FreeValue"] = "wolne: ",

        // Avalonia-specific
        ["MainWindow.SubtitleShort"] = "Bezpieczna analiza i czyszczenie dysków",
        ["Dash.FreePrefix"] = "Wolne ",
        ["Dash.DrivesTitle"] = "Dyski i partycje",
        ["Dash.TotalOps"] = "Operacji czyszczenia",
        ["Audit.Hint"] = "Historia wszystkich operacji czyszczenia i kwarantanny.",
        ["Quarantine.Hint"] = "Duże i podejrzane pliki trafiają tutaj przed usunięciem.",
        ["Dup.DescriptionShort"] = "Znajduje pliki o identycznej zawartości (po hashu) w wybranych obszarach.",
        ["Dup.GroupCol"] = "Grupa",
        ["Common.ExportTooltip"] = "Zapisz raport kandydatów do pliku",
        ["Common.Time"] = "Czas",
        ["Settings.AccentColorShort"] = "Akcent",
        ["Settings.ThemeLabel"] = "Motyw",
        ["Settings.DarkTheme"] = "Ciemny motyw",
        ["Settings.SystemCard"] = "System",
        ["Settings.AutoCleanThresholdMb"] = "Próg auto-czyszczenia (MB)",
        ["Col.Expires"] = "Wygasa",
        ["Col.QuarantinedAt"] = "Umieszczono",

        // CLI
        ["Cli.UnknownCommand"] = "Nieznana komenda: {0}",
        ["Cli.ScannedLine"] = "Przeskanowane pliki: {0:N0}, kandydaci: {1}",
        ["Cli.Potential"] = "Potencjalnie do odzyskania: {0}",
        ["Cli.MoreCandidates"] = "... i jeszcze {0} kandydatów.",
        ["Cli.CandidatesToProcess"] = "Kandydaci do przetworzenia: {0} ({1})",
        ["Cli.ProcessedFreed"] = "Przetworzono: {0}, zwolniono: {1}",
        ["Cli.SpecifyRoots"] = "Podaj --roots d1,d2 do wyszukiwania duplikatów",
        ["Cli.DuplicatesFound"] = "Znaleziono duplikatów: {0}",
        ["Cli.AuditEntries"] = "Wpisów: {0}",
        ["Cli.QuarantineUsage"] = "quarantine: podaj list|restore <id>|remove <id>|purge",
        ["Cli.SpecifyQuarantineId"] = "Podaj id wpisu kwarantanny",
        ["Cli.PurgedExpired"] = "Usunięto przedawnione wpisy: {0}",
        ["Cli.UpdateAvailableLong"] = "Dostępna wersja: {0} ({1})",
    };
}
