namespace SafeDiskCleaner.Core.Localization;

/// <summary>English strings.</summary>
internal static class En
{
    public static readonly IReadOnlyDictionary<string, string> Map = new Dictionary<string, string>
    {
        // Common
        ["Common.Cancel"] = "Cancel",
        ["Common.Delete"] = "Delete",
        ["Common.Restore"] = "Restore",
        ["Common.SelectAll"] = "Select all",
        ["Common.Deselect"] = "Deselect",
        ["Common.Clear"] = "Clear",
        ["Common.Continue"] = "Continue",
        ["Common.Date"] = "Date",
        ["Common.Details"] = "Details",
        ["Common.Size"] = "Size",
        ["Common.Path"] = "Path",
        ["Common.Status"] = "Status",
        ["Common.Actions"] = "Actions",
        ["Common.Action"] = "Action",
        ["Common.Browse"] = "Browse...",
        ["Common.OriginalPath"] = "Original path",
        ["Common.Original"] = "Original",
        ["Common.LastAccess"] = "Last access",
        ["Common.ExportCsv"] = "Export CSV",
        ["Common.ExportCsvTooltip"] = "Save the candidate report to a CSV file",
        ["Common.ClearSelected"] = "Clear selection",
        ["Common.CleanupResult"] = "Cleanup result",
        ["Common.NothingSelected"] = "Nothing selected.",
        ["Common.ProcessedFreed"] = "Processed {0}, freed {1}.",
        ["Common.DryRunFreed"] = "Dry-run: would have freed {0}.",
        ["Common.Error"] = "Error: {0}",
        ["C.DaysShort"] = "{0} d.",

        // Navigation / shell
        ["Nav.Dashboard"] = "Dashboard",
        ["Nav.Scan"] = "Scan",
        ["Nav.Duplicates"] = "Duplicates",
        ["Nav.Quarantine"] = "Quarantine",
        ["Nav.Settings"] = "Settings",
        ["Nav.AuditLog"] = "Audit Log",
        ["Nav.Apps"] = "Apps",
        ["Apps.Title"] = "Applications",
        ["Apps.Description"] = "Official uninstallers of the programs installed on this machine. A quiet mode is preferred when the vendor provides one.",
        ["Apps.NameCol"] = "Name",
        ["Apps.VersionCol"] = "Version",
        ["Apps.PublisherCol"] = "Publisher",
        ["Apps.SizeCol"] = "Size",
        ["Apps.UninstallBtn"] = "Uninstall",
        ["Apps.RefreshBtn"] = "Refresh list",
        ["Apps.Empty"] = "No applications with an uninstaller were found.",
        ["Apps.ConfirmTitle"] = "Uninstall",
        ["Apps.ConfirmMsg"] = "Run the official uninstaller for “{0}”?",
        ["Apps.Launched"] = "The uninstaller for “{0}” was started.",
        ["Apps.Error"] = "Uninstall error: {0}",
        ["Apps.WindowsOnly"] = "The applications list is available on Windows only.",
        ["Scan.TreemapToggle"] = "Results map",
        ["MainWindow.Subtitle"] = "Safe analysis and cleanup of Windows disks",

        // Dashboard
        ["Dash.Subtitle"] = "Disk status and cleanup statistics",
        ["Dash.QuickActions"] = "Quick actions",
        ["Dash.FreedHistory"] = "Freed in the last 14 days",
        ["Dash.ScanNow"] = "Scan now",
        ["Dash.FreedTotal"] = "Freed in total",
        ["Dash.InQuarantine"] = "In quarantine",
        ["Dash.LastScan"] = "Last scan",
        ["Dash.DrivesCount"] = "Drives",
        ["Dash.UnderAnalysis"] = "analyzed",
        ["Dash.Drives"] = "Drives",

        // Audit
        ["Audit.Description"] = "Log of all cleanup operations stored in SQLite (EF Core).",
        ["Audit.ClearLog"] = "Clear log",
        ["Audit.EmptyTitle"] = "Log is empty",
        ["Audit.EmptyText"] = "All performed cleanup operations will appear here.",
        ["Audit.ConfirmClearMsg"] = "All audit records will be deleted. Continue?",

        // Quarantine
        ["Quarantine.Description"] = "Files that SafeDisk moved before deletion so they can be restored. Here you can put them back or delete them permanently. Retention is configured in “Settings”.",
        ["Quarantine.Clear"] = "Empty quarantine",
        ["Quarantine.EmptyTitle"] = "Quarantine is empty",
        ["Quarantine.EmptyText"] = "Files moved before permanent deletion will appear here.",
        ["Quarantine.DeleteConfirmTitle"] = "Delete from quarantine",
        ["Quarantine.DeleteConfirmMsg"] = "The file will be deleted permanently:\n{0}",
        ["Quarantine.ClearConfirmMsg"] = "All quarantined files will be deleted permanently. Continue?",
        ["Quarantine.Cleared"] = "Quarantine cleared ({0} entries).",
        ["Quarantine.RestoreFailed"] = "Restore failed: {0}",

        // Duplicates
        ["Dup.Title"] = "Duplicate finder",
        ["Dup.Description"] = "Files larger than 4 KB are compared by BLAKE3 hash. Scan scope: paths from the “Scan” tab or all drives if not specified. When “Select all” is chosen, the newest copy of each group is always kept.",
        ["Dup.Find"] = "Find duplicates",
        ["Dup.Searching"] = "Searching...",
        ["Dup.ResultsTitle"] = "Duplicates",
        ["Dup.NeedRoots"] = "Specify paths for duplicate analysis.",
        ["Dup.NotFound"] = "No duplicates found.",
        ["Dup.Found"] = "Found duplicates: {0}.",
        ["Dup.Cancelled"] = "Duplicate search cancelled.",

        // Scan
        ["Scan.AreaTitle"] = "Scan scope",
        ["Scan.CustomRootsHint"] = "Additional paths to scan (comma separated)...",
        ["Scan.MediumCheckbox"] = "Medium (updates, packages)",
        ["Scan.ToRecycleBin"] = "Use recycle bin",
        ["Scan.ToRecycleBinTooltip"] = "Small files are moved to the Windows recycle bin instead of being deleted permanently. Large files always go to the SafeDisk quarantine.",
        ["Scan.NotUsedDays"] = "Not used for days:",
        ["Scan.Analyze"] = "Analyze",
        ["Scan.Scanning"] = "Scanning...",
        ["Scan.CleanRecycleBin"] = "Empty recycle bin",
        ["Scan.CleanRecycleBinTooltip"] = "Permanently delete all files from the Windows recycle bin",
        ["Scan.Potential"] = "Potentially recoverable",
        ["Scan.FilesScanned"] = "Files scanned",
        ["Scan.CandidatesCount"] = "Candidates",
        ["Scan.ElapsedTime"] = "Elapsed time",
        ["Scan.Candidates"] = "Candidates",
        ["Scan.OnlySafe"] = "Only safe",
        ["Scan.OnlySafeTooltip"] = "Select only candidates with Safe risk level",
        ["Scan.AutoClean"] = "Auto-cleanup",
        ["Scan.CleanSelected"] = "Clean selected",
        ["Scan.Filters"] = "Filters:",
        ["Scan.SearchHint"] = "Search by path...",
        ["Scan.ResetFilters"] = "Reset filters",
        ["Scan.PickFolders"] = "Choose folders or drives to scan",
        ["Scan.NoCandidates"] = "No cleanup candidates found.",
        ["Scan.Completed"] = "Scanned {0:N0} files, found candidates: {1}.",
        ["Scan.Cancelled"] = "Scan cancelled.",
        ["Scan.Error"] = "Scan error: {0}",
        ["Scan.DeleteWithoutBinTitle"] = "Delete without recycle bin",
        ["Scan.DeleteWithoutBinMsg"] = "Files will not be moved to the recycle bin. Large files will go to the SafeDisk quarantine. Continue?",

        // Recycle bin
        ["RecycleBin.CleanConfirmTitle"] = "Empty recycle bin",
        ["RecycleBin.CleanConfirmMsg"] = "This will permanently delete all files in the recycle bin. Continue?",
        ["RecycleBin.Cleaned"] = "Recycle bin emptied.",
        ["RecycleBin.CleanFailed"] = "Failed to empty the recycle bin.",

        // Settings
        ["Settings.InterfaceCard"] = "Interface",
        ["Settings.Theme"] = "Theme:",
        ["Settings.AccentColor"] = "Accent color:",
        ["Settings.Language"] = "Language:",
        ["Settings.CleaningCard"] = "Cleanup",
        ["Settings.RetentionDays"] = "Quarantine retention (days):",
        ["Settings.AutoThreshold"] = "Auto confidence threshold (%):",
        ["Settings.ProgramCard"] = "Application",
        ["Settings.Version"] = "Version:",
        ["Settings.DataDir"] = "Data directory:",
        ["Settings.CheckUpdates"] = "Check for updates",
        ["Settings.ExclusionsCard"] = "Exclusions",
        ["Settings.ScheduleCard"] = "Cleanup schedule",
        ["Settings.ScheduleEnable"] = "Run cleanup on a schedule",
        ["Settings.ScheduleDaily"] = "Daily",
        ["Settings.ScheduleWeekly"] = "Weekly",
        ["Settings.ScheduleTimeLabel"] = "Time (HH:mm):",
        ["Settings.ScheduleApplied"] = "Schedule activated.",
        ["Settings.ScheduleRemoved"] = "Schedule removed.",
        ["Settings.ScheduleUnsupported"] = "Scheduling is not supported on this system.",
        ["Settings.ScheduleMissingCli"] = "SafeDiskCleaner.Cli was not found next to the application.",
        ["Settings.ScheduleError"] = "Schedule error: {0}",
        ["Settings.ExclusionsHint"] = "One per line: a path or a * ? pattern. These paths are never scanned.",
        ["Settings.UpdateAvailable"] = "Version {0} available",
        ["Settings.UpToDate"] = "Up to date ({0})",

        // Update flow
        ["Update.Checking"] = "Loading...",
        ["Update.Installing"] = "Installing...",
        ["Update.AvailablePrefix"] = "Version ",
        ["Update.Install"] = "Update",

        // Filters / export / cleanup
        ["Filter.AllCategories"] = "All categories",
        ["Filter.AllRisks"] = "All risks",
        ["Export.SaveReport"] = "Save candidate report",
        ["Export.Saved"] = "Report saved: {0}",
        ["Export.Error"] = "Export error: {0}",
        ["Cleanup.Error"] = "Cleanup error: {0}",

        // Grid columns
        ["Col.Category"] = "Category",
        ["Col.Risk"] = "Risk",
        ["Col.Recommendation"] = "Recommendation",

        // Inline fragments between bound runs
        ["Frag.FreeInline"] = " · free ",
        ["Frag.Selected"] = " selected · ",
        ["Frag.Of"] = " of ",
        ["Frag.Files"] = " files · ",
        ["Frag.Candidates"] = " candidates",
        ["Frag.TotalPrefix"] = "· Total ",
        ["Frag.Operations"] = " operations",
        ["Frag.FilesWord"] = " files",
        ["Frag.CandidatesWord"] = " candidates",
        ["Dash.FreeValue"] = "free: ",

        // Avalonia-specific
        ["MainWindow.SubtitleShort"] = "Safe analysis and disk cleanup",
        ["Dash.FreePrefix"] = "Free ",
        ["Dash.DrivesTitle"] = "Drives & partitions",
        ["Dash.TotalOps"] = "Cleanup operations",
        ["Audit.Hint"] = "History of all cleanup and quarantine operations.",
        ["Quarantine.Hint"] = "Large and suspicious files are moved here before deletion.",
        ["Dup.DescriptionShort"] = "Finds files with identical content (by hash) in the selected areas.",
        ["Dup.GroupCol"] = "Group",
        ["Common.ExportTooltip"] = "Save the candidate report to a file",
        ["Common.Time"] = "Time",
        ["Settings.AccentColorShort"] = "Accent",
        ["Settings.ThemeLabel"] = "Theme",
        ["Settings.DarkTheme"] = "Dark theme",
        ["Settings.SystemCard"] = "System",
        ["Settings.AutoCleanThresholdMb"] = "Auto-clean threshold (MB)",
        ["Col.Expires"] = "Expires",
        ["Col.QuarantinedAt"] = "Quarantined",

        // CLI
        ["Cli.UnknownCommand"] = "Unknown command: {0}",
        ["Cli.ScannedLine"] = "Files scanned: {0:N0}, candidates: {1}",
        ["Cli.Potential"] = "Potentially recoverable: {0}",
        ["Cli.MoreCandidates"] = "... and {0} more candidates.",
        ["Cli.CandidatesToProcess"] = "Candidates to process: {0} ({1})",
        ["Cli.ProcessedFreed"] = "Processed: {0}, freed: {1}",
        ["Cli.SpecifyRoots"] = "Specify --roots d1,d2 for duplicate search",
        ["Cli.DuplicatesFound"] = "Duplicates found: {0}",
        ["Cli.AuditEntries"] = "Entries: {0}",
        ["Cli.QuarantineUsage"] = "quarantine: specify list|restore <id>|remove <id>|purge",
        ["Cli.SpecifyQuarantineId"] = "Specify a quarantine entry id",
        ["Cli.PurgedExpired"] = "Purged expired entries: {0}",
        ["Cli.UpdateAvailableLong"] = "Version available: {0} ({1})",
    };
}
