namespace SafeDiskCleaner.Core.Localization;

/// <summary>Ukrainian strings (source of truth for key names).</summary>
internal static class Uk
{
    public static readonly IReadOnlyDictionary<string, string> Map = new Dictionary<string, string>
    {
        // Common
        ["Common.Cancel"] = "Скасувати",
        ["Common.Delete"] = "Видалити",
        ["Common.Restore"] = "Відновити",
        ["Common.SelectAll"] = "Вибрати все",
        ["Common.Deselect"] = "Зняти",
        ["Common.Clear"] = "Очистити",
        ["Common.Continue"] = "Продовжити",
        ["Common.Date"] = "Дата",
        ["Common.Details"] = "Деталі",
        ["Common.Size"] = "Розмір",
        ["Common.Path"] = "Шлях",
        ["Common.Status"] = "Статус",
        ["Common.Actions"] = "Дії",
        ["Common.Action"] = "Дія",
        ["Common.Browse"] = "Огляд...",
        ["Common.OriginalPath"] = "Оригінальний шлях",
        ["Common.Original"] = "Оригінал",
        ["Common.LastAccess"] = "Останній доступ",
        ["Common.ExportCsv"] = "Експорт CSV",
        ["Common.ExportCsvTooltip"] = "Зберегти звіт про кандидатів у файл CSV",
        ["Common.ClearSelected"] = "Очистити вибрані",
        ["Common.CleanupResult"] = "Результат очищення",
        ["Common.NothingSelected"] = "Нічого не вибрано.",
        ["Common.ProcessedFreed"] = "Оброблено {0}, звільнено {1}.",
        ["Common.DryRunFreed"] = "Dry-run: було б звільнено {0}.",
        ["Common.Error"] = "Помилка: {0}",
        ["C.DaysShort"] = "{0} дн.",

        // Navigation / shell
        ["Nav.Dashboard"] = "Огляд",
        ["Nav.Scan"] = "Сканування",
        ["Nav.Duplicates"] = "Дублікати",
        ["Nav.Quarantine"] = "Карантин",
        ["Nav.Settings"] = "Налаштування",
        ["Nav.AuditLog"] = "Журнал аудиту",
        ["Nav.Apps"] = "Застосунки",
        ["Apps.Title"] = "Застосунки",
        ["Apps.Description"] = "Офіційні деінсталятори програм, встановлених на цій машині. Спершу пропонується тихий режим, якщо він передбачений розробником.",
        ["Apps.NameCol"] = "Назва",
        ["Apps.VersionCol"] = "Версія",
        ["Apps.PublisherCol"] = "Видавець",
        ["Apps.SizeCol"] = "Розмір",
        ["Apps.UninstallBtn"] = "Видалити",
        ["Apps.RefreshBtn"] = "Оновити список",
        ["Apps.Empty"] = "Не знайдено жодного застосунку з деінсталятором.",
        ["Apps.ConfirmTitle"] = "Деінсталяція",
        ["Apps.ConfirmMsg"] = "Запустити офіційний деінсталятор «{0}»?",
        ["Apps.Launched"] = "Деінсталятор «{0}» запущено.",
        ["Apps.Error"] = "Помилка деінсталяції: {0}",
        ["Apps.WindowsOnly"] = "Список застосунків доступний лише на Windows.",
        ["Scan.TreemapToggle"] = "Карта результатів",
        ["MainWindow.Subtitle"] = "Безпечний аналіз і очищення дисків Windows",

        // Dashboard
        ["Dash.Subtitle"] = "Стан дисків і статистика очищення",
        ["Dash.QuickActions"] = "Швидкі дії",
        ["Dash.FreedHistory"] = "Звільнено за 14 днів",
        ["Dash.ScanNow"] = "Сканувати зараз",
        ["Dash.FreedTotal"] = "Звільнено за весь час",
        ["Dash.InQuarantine"] = "У карантині",
        ["Dash.LastScan"] = "Останнє сканування",
        ["Dash.DrivesCount"] = "Дисків",
        ["Dash.UnderAnalysis"] = "під аналізом",
        ["Dash.Drives"] = "Диски",

        // Audit
        ["Audit.Description"] = "Журнал всіх операцій очищення, що зберігається в SQLite (EF Core).",
        ["Audit.ClearLog"] = "Очистити лог",
        ["Audit.EmptyTitle"] = "Журнал порожній",
        ["Audit.EmptyText"] = "Тут з'являться всі виконані операції очищення.",
        ["Audit.ConfirmClearMsg"] = "Всі записи аудиту буде видалено. Продовжити?",

        // Quarantine
        ["Quarantine.Description"] = "Файли, які SafeDisk перемістив перед видаленням, щоб їх можна було відновити. Тут їх можна повернути на місце або видалити остаточно. Термін зберігання налаштовується у «Налаштуваннях».",
        ["Quarantine.Clear"] = "Очистити карантин",
        ["Quarantine.EmptyTitle"] = "Карантин порожній",
        ["Quarantine.EmptyText"] = "Тут з'являться файли, переміщені перед остаточним видаленням.",
        ["Quarantine.DeleteConfirmTitle"] = "Видалити з карантину",
        ["Quarantine.DeleteConfirmMsg"] = "Файл буде видалено безповоротно:\n{0}",
        ["Quarantine.ClearConfirmMsg"] = "Усі карантинні файли буде видалено безповоротно. Продовжити?",
        ["Quarantine.Cleared"] = "Карантин очищено ({0} записів).",
        ["Quarantine.RestoreFailed"] = "Не вдалося відновити: {0}",

        // Duplicates
        ["Dup.Title"] = "Пошук дублікатів",
        ["Dup.Description"] = "Аналізуються файли розміром понад 4 КБ за BLAKE3-хешем. Шлях аналізу: шляхи з вкладки «Сканування» або всі диски, якщо не вказано. При виборі «Вибрати все» завжди зберігається одна найновіша копія кожної групи.",
        ["Dup.Find"] = "Знайти дублікати",
        ["Dup.Searching"] = "Пошук...",
        ["Dup.ResultsTitle"] = "Дублікати",
        ["Dup.NeedRoots"] = "Вкажіть шляхи для аналізу дублікатів.",
        ["Dup.NotFound"] = "Дублікатів не знайдено.",
        ["Dup.Found"] = "Знайдено дублікатів: {0}.",
        ["Dup.Cancelled"] = "Пошук дублікатів скасовано.",

        // Scan
        ["Scan.AreaTitle"] = "Область аналізу",
        ["Scan.CustomRootsHint"] = "Додаткові шляхи для аналізу (через кому)...",
        ["Scan.MediumCheckbox"] = "Medium (оновлення, пакети)",
        ["Scan.ToRecycleBin"] = "У кошик",
        ["Scan.ToRecycleBinTooltip"] = "Малі файли переміщуються в кошик Windows замість остаточного видалення. Великі файли завжди йдуть у карантин.",
        ["Scan.NotUsedDays"] = "Не використано днів:",
        ["Scan.Analyze"] = "Аналізувати",
        ["Scan.Scanning"] = "Сканування...",
        ["Scan.CleanRecycleBin"] = "Очистити кошик",
        ["Scan.CleanRecycleBinTooltip"] = "Назавжди видалити всі файли з кошика Windows",
        ["Scan.Potential"] = "Потенційно звільниться",
        ["Scan.FilesScanned"] = "Файлів проскановано",
        ["Scan.CandidatesCount"] = "Кандидатів",
        ["Scan.ElapsedTime"] = "Час аналізу",
        ["Scan.Candidates"] = "Кандидати",
        ["Scan.OnlySafe"] = "Тільки безпечні",
        ["Scan.OnlySafeTooltip"] = "Вибрати лише кандидатів із рівнем ризику Safe",
        ["Scan.AutoClean"] = "Авто-очищення",
        ["Scan.CleanSelected"] = "Очистити вибране",
        ["Scan.Filters"] = "Фільтри:",
        ["Scan.SearchHint"] = "Пошук за шляхом...",
        ["Scan.ResetFilters"] = "Скинути фільтри",
        ["Scan.PickFolders"] = "Виберіть папки або диски для аналізу",
        ["Scan.NoCandidates"] = "Не знайдено кандидатів на очищення.",
        ["Scan.Completed"] = "Проскановано {0:N0} файлів, знайдено кандидатів: {1}.",
        ["Scan.Cancelled"] = "Сканування скасовано.",
        ["Scan.Error"] = "Помилка сканування: {0}",
        ["Scan.DeleteWithoutBinTitle"] = "Видалення без кошика",
        ["Scan.DeleteWithoutBinMsg"] = "Файли не будуть переміщені в кошик. Великі файли потраплять у карантин SafeDisk. Продовжити?",

        // Recycle bin
        ["RecycleBin.CleanConfirmTitle"] = "Очищення кошика",
        ["RecycleBin.CleanConfirmMsg"] = "Це назавжди видалить усі файли з кошика. Продовжити?",
        ["RecycleBin.Cleaned"] = "Кошик очищено.",
        ["RecycleBin.CleanFailed"] = "Не вдалося очистити кошик.",

        // Settings
        ["Settings.InterfaceCard"] = "Інтерфейс",
        ["Settings.Theme"] = "Тема:",
        ["Settings.AccentColor"] = "Акцентний колір:",
        ["Settings.Language"] = "Мова:",
        ["Settings.CleaningCard"] = "Очищення",
        ["Settings.RetentionDays"] = "Термін зберігання карантину (днів):",
        ["Settings.AutoThreshold"] = "Auto-поріг впевненості (%):",
        ["Settings.ProgramCard"] = "Програма",
        ["Settings.Version"] = "Версія:",
        ["Settings.DataDir"] = "Каталог даних:",
        ["Settings.CheckUpdates"] = "Перевірити оновлення",
        ["Settings.ExclusionsCard"] = "Виключення",
        ["Settings.ScheduleCard"] = "Розклад авто-очищення",
        ["Settings.ScheduleEnable"] = "Запускати очищення за розкладом",
        ["Settings.ScheduleDaily"] = "Щодня",
        ["Settings.ScheduleWeekly"] = "Щотижня",
        ["Settings.ScheduleTimeLabel"] = "Час (HH:mm):",
        ["Settings.ScheduleApplied"] = "Розклад активовано.",
        ["Settings.ScheduleRemoved"] = "Розклад вимкнено.",
        ["Settings.ScheduleUnsupported"] = "Планувальник не підтримується на цій системі.",
        ["Settings.ScheduleMissingCli"] = "Не знайдено SafeDiskCleaner.Cli поруч із застосунком.",
        ["Settings.ScheduleError"] = "Помилка розкладу: {0}",
        ["Settings.ExclusionsHint"] = "По одному на рядок: шлях або шаблон із * та ?. Ці шляхи ніколи не скануватимуться.",
        ["Settings.UpdateAvailable"] = "Доступна версія {0}",
        ["Settings.UpToDate"] = "Встановлена остання версія ({0})",

        // Update flow
        ["Update.Checking"] = "Завантаження...",
        ["Update.Installing"] = "Встановлення...",
        ["Update.AvailablePrefix"] = "Доступна версія ",
        ["Update.Install"] = "Оновити",

        // Filters / export / cleanup
        ["Filter.AllCategories"] = "Усі категорії",
        ["Filter.AllRisks"] = "Усі ризики",
        ["Export.SaveReport"] = "Зберегти звіт про кандидатів",
        ["Export.Saved"] = "Звіт збережено: {0}",
        ["Export.Error"] = "Помилка експорту: {0}",
        ["Cleanup.Error"] = "Помилка очищення: {0}",

        // Grid columns
        ["Col.Category"] = "Категорія",
        ["Col.Risk"] = "Ризик",
        ["Col.Recommendation"] = "Рекомендація",

        // Inline fragments between bound runs
        ["Frag.FreeInline"] = " · вільно ",
        ["Frag.Selected"] = " вибрано · ",
        ["Frag.Of"] = " з ",
        ["Frag.Files"] = " файлів · ",
        ["Frag.Candidates"] = " кандидатів",
        ["Frag.TotalPrefix"] = "· Всього ",
        ["Frag.Operations"] = " операцій",
        ["Frag.FilesWord"] = " файлів",
        ["Frag.CandidatesWord"] = " кандидатів",
        ["Dash.FreeValue"] = "вільно: ",

        // Avalonia-specific
        ["MainWindow.SubtitleShort"] = "Безпечний аналіз і очищення дисків",
        ["Dash.FreePrefix"] = "Вільно ",
        ["Dash.DrivesTitle"] = "Диски та розділи",
        ["Dash.TotalOps"] = "Операцій очищено",
        ["Audit.Hint"] = "Історія всіх операцій очищення та карантину.",
        ["Quarantine.Hint"] = "Великі та підозрілі файли переміщуються сюди перед видаленням.",
        ["Dup.DescriptionShort"] = "Знаходить файли з однаковим вмістом (за хешем) у вибраних областях.",
        ["Dup.GroupCol"] = "Група",
        ["Common.ExportTooltip"] = "Зберегти звіт про кандидатів у файл",
        ["Common.Time"] = "Час",
        ["Settings.AccentColorShort"] = "Акцент",
        ["Settings.ThemeLabel"] = "Тема",
        ["Settings.DarkTheme"] = "Темна тема",
        ["Settings.SystemCard"] = "Система",
        ["Settings.AutoCleanThresholdMb"] = "Поріг авто-очищення (MB)",
        ["Col.Expires"] = "Завершується",
        ["Col.QuarantinedAt"] = "Поміщено",

        // CLI
        ["Cli.UnknownCommand"] = "Невідома команда: {0}",
        ["Cli.ScannedLine"] = "Проскановано файлів: {0:N0}, кандидатів: {1}",
        ["Cli.Potential"] = "Потенційно звільниться: {0}",
        ["Cli.MoreCandidates"] = "... ще {0} кандидатів.",
        ["Cli.CandidatesToProcess"] = "Кандидатів до обробки: {0} ({1})",
        ["Cli.ProcessedFreed"] = "Оброблено: {0}, звільнено: {1}",
        ["Cli.SpecifyRoots"] = "Для пошуку дублікатів вкажіть --roots d1,d2",
        ["Cli.DuplicatesFound"] = "Дублікатів знайдено: {0}",
        ["Cli.AuditEntries"] = "Записів: {0}",
        ["Cli.QuarantineUsage"] = "quarantine: вкажіть list|restore <id>|remove <id>|purge",
        ["Cli.SpecifyQuarantineId"] = "Вкажіть id карантинного запису",
        ["Cli.PurgedExpired"] = "Видалено прострочених записів: {0}",
        ["Cli.UpdateAvailableLong"] = "Доступна версія: {0} ({1})",
    };
}
